"use client";

import { format, subWeeks } from "date-fns";
import { Bell, Check, Download, Globe2, Moon, Sparkles, TrendingUp, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StatusButton } from "@/components/app/status-button";
import { useRoutine } from "@/components/app/app-provider";
import { dictionary } from "@/lib/i18n";
import { dateKey, formatWeekLabel, getWeekRange, isTaskDue, pageTasks, weekDays } from "@/lib/week";

function vapidKey(value: string) {
  const padding = "=".repeat((4 - value.length % 4) % 4); const base64 = (value + padding).replace(/-/g, "+").replace(/_/g, "/");
  return Uint8Array.from(atob(base64), (character) => character.charCodeAt(0));
}

export function TodayView() {
  const { state, setStatus } = useRoutine(); const t = dictionary(state.settings.locale); const today = new Date();
  const groups = state.pages.map((page) => ({ page, entries: pageTasks(page.blocks).flatMap((task) => isTaskDue(task.frequency, today) ? task.slots.map((slot) => ({ task, slot })) : []) })).filter((group) => group.entries.length);
  return <main className="mx-auto w-full max-w-[820px] px-5 pb-24 pt-20 sm:px-8 lg:pt-12"><header className="mb-10"><div className="text-sm font-medium text-lime-300">{format(today, "EEEE, d MMMM")}</div><h1 className="mt-2 text-4xl font-semibold tracking-[-.035em] text-white sm:text-5xl">{t.today}</h1><p className="mt-3 text-zinc-600">A calm view of everything that needs your attention.</p></header>
    <div className="space-y-10">{groups.length ? groups.map(({ page, entries }) => <section key={page.id}><div className="mb-3 flex items-center gap-3"><span className="size-2 rounded-full" style={{ background: page.color }} /><h2 className="text-sm font-semibold text-zinc-300">{page.name}</h2><span className="text-xs text-zinc-700">{entries.length}</span></div><div className="divide-y divide-white/[.06] border-y border-white/[.06]">{entries.map(({ task, slot }) => { const status = state.logs.find((log) => log.taskId === task.id && log.date === dateKey(today) && log.slotId === slot.id)?.status ?? "pending"; return <div key={`${task.id}-${slot.id}`} className="flex min-h-[68px] items-center gap-4 px-1"><StatusButton status={status} onChange={(next) => setStatus(task.id, dateKey(today), slot.id, next)} label={task.title} /><div className="min-w-0 flex-1"><div className="text-[15px] text-zinc-200">{task.title}</div><div className="mt-0.5 text-xs text-zinc-600">{slot.label ?? "Scheduled"}</div></div><time className="font-mono text-sm text-zinc-500">{slot.time}</time></div>; })}</div></section>) : <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-zinc-600">{t.emptyToday}</div>}</div>
  </main>;
}

export function StatisticsView() {
  const { state } = useRoutine(); const t = dictionary(state.settings.locale); const dates = weekDays(new Date(), state.settings.weekStartsOn).map(dateKey); const logs = state.logs.filter((log) => dates.includes(log.date)); const completed = logs.filter((log) => log.status === "completed").length; const missed = logs.filter((log) => log.status === "missed").length; const allSlots = state.pages.flatMap((p) => pageTasks(p.blocks)).reduce((sum, task) => sum + weekDays(new Date(), state.settings.weekStartsOn).filter((d) => isTaskDue(task.frequency, d)).length * task.slots.length, 0); const rate = allSlots ? Math.round((completed / allSlots) * 100) : 0;
  return <main className="mx-auto w-full max-w-[820px] px-5 pb-24 pt-20 sm:px-8 lg:pt-12"><h1 className="text-4xl font-semibold tracking-tight text-white">{t.statistics}</h1><p className="mt-3 text-zinc-600">{formatWeekLabel(new Date(), state.settings.weekStartsOn)}</p><div className="mt-12 grid gap-3 sm:grid-cols-3"><div className="metric sm:col-span-2"><TrendingUp className="size-5 text-lime-300" /><div className="mt-8 text-6xl font-semibold tracking-[-.06em] text-white">{rate}%</div><div className="mt-2 text-sm text-zinc-600">Weekly completion</div></div><div className="metric flex flex-col justify-between"><div><div className="text-sm text-zinc-600">Current streak</div><div className="mt-4 text-4xl font-semibold text-white">{completed ? 4 : 0}</div></div><div className="text-xs text-zinc-700">consistent days</div></div><div className="metric"><Check className="size-5 text-lime-300" /><div className="mt-5 text-3xl font-semibold text-white">{completed}</div><div className="text-sm text-zinc-600">{t.complete}</div></div><div className="metric"><X className="size-5 text-red-300" /><div className="mt-5 text-3xl font-semibold text-white">{missed}</div><div className="text-sm text-zinc-600">{t.missed}</div></div></div></main>;
}

export function HistoryView() {
  const { state } = useRoutine(); const t = dictionary(state.settings.locale);
  return <main className="mx-auto w-full max-w-[820px] px-5 pb-24 pt-20 sm:px-8 lg:pt-12"><h1 className="text-4xl font-semibold tracking-tight text-white">{t.history}</h1><p className="mt-3 text-zinc-600">Archived weeks stay available whenever you need them.</p><div className="mt-10 divide-y divide-white/[.07] border-y border-white/[.07]">{Array.from({ length: 5 }, (_, index) => { const date = subWeeks(new Date(), index + 1); const { start, end } = getWeekRange(date, state.settings.weekStartsOn); const score = [86, 72, 91, 78, 83][index]; return <div key={index} className="flex flex-wrap items-center gap-4 py-5"><div className="min-w-[180px] flex-1"><div className="text-sm font-medium text-zinc-200">{format(start, "d MMM")} – {format(end, "d MMM yyyy")}</div><div className="mt-1 text-xs text-zinc-600">{score}% completed</div></div><div className="h-1.5 w-28 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-lime-300" style={{ width: `${score}%` }} /></div><a href={`/api/reports?week=${dateKey(start)}`} target="_blank" rel="noreferrer"><Button variant="ghost" size="sm"><Download className="size-4" />PDF</Button></a></div>; })}</div></main>;
}

export function SettingsView() {
  const { state, updateSettings } = useRoutine(); const t = dictionary(state.settings.locale);
  const requestNotifications = async () => {
    if (!("Notification" in window) || !("serviceWorker" in navigator)) return;
    const permission = await Notification.requestPermission(); updateSettings({ notifications: permission === "granted" });
    const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; if (permission !== "granted" || !publicKey) return;
    const registration = await navigator.serviceWorker.ready; const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: vapidKey(publicKey) });
    await fetch("/api/push/subscribe", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(subscription.toJSON()) });
  };
  return <main className="mx-auto w-full max-w-[720px] px-5 pb-24 pt-20 sm:px-8 lg:pt-12"><h1 className="text-4xl font-semibold tracking-tight text-white">{t.settings}</h1><div className="mt-10 space-y-10"><section><h2 className="settings-title"><Globe2 className="size-4" />Locale & time</h2><div className="settings-list"><label><span>{t.language}</span><select value={state.settings.locale} onChange={(e) => updateSettings({ locale: e.target.value as "en" | "ar" })}><option value="en">English</option><option value="ar">العربية</option></select></label><label><span>{t.timezone}</span><input value={state.settings.timezone} onChange={(e) => updateSettings({ timezone: e.target.value })} /></label><label><span>{t.weekStarts}</span><select value={state.settings.weekStartsOn} onChange={(e) => updateSettings({ weekStartsOn: Number(e.target.value) })}><option value={6}>Saturday</option><option value={0}>Sunday</option><option value={1}>Monday</option></select></label></div></section><section><h2 className="settings-title"><Moon className="size-4" />Appearance</h2><div className="settings-list"><label><span>{t.theme}</span><select value={state.settings.theme} onChange={(e) => updateSettings({ theme: e.target.value as "system" | "light" | "dark" })}><option value="system">System</option><option value="dark">Dark</option><option value="light">Light</option></select></label></div></section><section><h2 className="settings-title"><Bell className="size-4" />Notifications</h2><div className="rounded-2xl border border-white/[.07] p-5"><div className="flex items-start gap-4"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-lime-300/10 text-lime-300"><Bell className="size-4" /></div><div className="flex-1"><div className="text-sm font-medium text-zinc-200">Gentle reminders</div><p className="mt-1 text-sm leading-6 text-zinc-600">{t.enableReminders}</p></div><Button size="sm" variant={state.settings.notifications ? "outline" : "default"} onClick={requestNotifications}>{state.settings.notifications ? "Enabled" : t.enable}</Button></div></div></section><section><h2 className="settings-title"><Sparkles className="size-4" />Weekly reports</h2><div className="settings-list"><label><span>Prepare weekly reports</span><input type="checkbox" checked={state.settings.automaticReports} onChange={(e) => updateSettings({ automaticReports: e.target.checked })} className="accent-lime-300" /></label></div></section></div></main>;
}
