"use client";

import { useState } from "react";
import { Clock3 } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { createClient } from "@/lib/supabase/client";

export default function LoginPage() {
  const router = useRouter(); const [mode, setMode] = useState<"login" | "signup">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const supabase = createClient(); if (!supabase) { router.push("/app"); return; } setBusy(true); setMessage(""); const result = mode === "login" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${location.origin}/auth/callback` } }); setBusy(false); if (result.error) setMessage(result.error.message); else if (mode === "signup" && !result.data.session) setMessage("Check your email to finish signing up."); else router.push("/app"); };
  return <main className="grid min-h-dvh place-items-center bg-[#0a0a0b] px-5 py-12"><div className="w-full max-w-sm"><div className="mb-10 flex items-center justify-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-lime-300 text-zinc-950"><Clock3 className="size-5" /></div><span className="text-xl font-semibold text-white">Ritual</span></div><div className="rounded-3xl border border-white/[.07] bg-white/[.018] p-6 sm:p-8"><h1 className="text-2xl font-semibold tracking-tight text-white">{mode === "login" ? "Welcome back" : "Create your space"}</h1><p className="mt-2 text-sm text-zinc-600">Small rituals, thoughtfully tracked.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="field-label">Email<input required className="input" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="field-label">Password<input required minLength={8} className="input" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} value={password} onChange={(e) => setPassword(e.target.value)} /></label>{message && <p className="text-sm text-zinc-400" role="status">{message}</p>}<Button disabled={busy} className="mt-2 w-full" type="submit">{busy ? "Please wait…" : mode === "login" ? "Log in" : "Sign up"}</Button></form><button className="mt-5 w-full text-center text-sm text-zinc-600 hover:text-zinc-300" onClick={() => setMode(mode === "login" ? "signup" : "login")}>{mode === "login" ? "New here? Create an account" : "Already have an account? Log in"}</button></div>{!process.env.NEXT_PUBLIC_SUPABASE_URL && <p className="mt-5 text-center text-xs text-zinc-700">Demo mode is active — any credentials continue locally.</p>}</div></main>;
}
